title: Jianfeng Chen
description: My Personal website
author: Jianfeng Chen
github: https://github.com/ginfung
about: CS.PhD.AI.SE.Infra
avatar_url: /static/img/ncsu_seal.png


enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-envelope
      link: "mailto:jchen37@ncsu.edu"
    - icon: fa-facebook
      link: "https://www.facebook.com/jfchen1992"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jianfengcs/"
    - icon: fa-github
      link: "https://github.com/ginfung"
    - icon: fa-wechat
      link: "/wechat/"
    - icon: fa-slideshare
      link: "https://www.slideshare.net/jianfengcs"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Resume
      url: /resume/
    - text: Publications
      url: https://scholar.google.com/citations?user=StXI8uQAAAAJ&hl=en&oi=ao
    - text: Projects
      url: /projects/
    - text: PDFs repo
      url: /pdf/
    - text: Blog
      url: /blog/

url: "https://jianfeng.us"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
