title: Jianfeng Chen
description: My Personal website
author: Jianfeng Chen
github: https://github.com/ginfung
about: CS.PhD.AI.SE.Infra
avatar_url: /static/img/ncsu_seal.png
statcounter_url: //c.statcounter.com/11220449/0/1d9684ef/0/  # ATTENTION: SET default.html sc_project

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  pdf:
    output: true
    permalink: /pdf/:path/

social:
    - icon: fa-envelope
      link: "mailto:jchen37@alumni.ncsu.edu"
    - icon: fa-facebook
      link: "https://www.facebook.com/jfchen1992"
    - icon: fa-twitter
      link: https://twitter.com/jianfeng0625
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jianfengcs/"
    - icon: fa-github
      link: "https://github.com/ginfung"
    - icon: fa-wechat
      link: "/wechat/"
    - icon: fa-slideshare
      link: "https://www.slideshare.net/jianfengcs"


share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Resume
      url: /resume/
    - text: Publications
      url: https://scholar.google.com/citations?user=StXI8uQAAAAJ&hl=en&oi=ao
    - text: Projects
      url: /projects/
    - text: Quick Links
      url: /qlink/
    - text: Blogs
      url: /blogs/

url: "https://jianfeng.us"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
highlighter: rouge



gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
